name: prod
on:
  push:
    branches:
      - 'main'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "*"
        target: "${{ secrets.PROD_DEPLOY_PATH }}"
        overwrite: true
        rm: true